no interrupt if reward on going
ptp-education/lando pull request #31
Opened 2022-11-02 17:43 UTC by benjaminZarate

If a new player scan and press success, the on going reward sequence is going to continue and not get interrupted by the new scan

2022-11-04 02:18 UTC, ptp-education requested changes
Tested the branch, but the functionality is still quite broken (spamming breaks game, scanning and getting success on a new Momo breaks game)

2022-11-04 02:18 UTC, ptp-education commented on Assets/scripts/episodes/lego_4/SpawnedWallMomo.cs
>          customizations_.Clear();
Why does this have to be a class variable?

2022-11-04 02:18 UTC, ptp-education commented on Assets/scripts/episodes/lego_4/SpawnedWallMomo.cs
> +        AudioPlayer.PlayAudio("audio/sfx/momo-happy");
Animations and sequences should be added to the GoTweenFlow, so that we either play the entire sequence or no part of it.

2022-11-04 02:18 UTC, ptp-education commented on Assets/scripts/episodes/lego_4/SpawnedWallMomo.cs
> +        flow_ = new GoTweenFlow();
Are we checking if flow is currently running?

2022-11-04 02:18 UTC, ptp-education commented on Assets/scripts/episodes/lego_4/SpawnedWallMomo.cs
> +        flow_ = new GoTweenFlow();
We shouldn't be instantiating a class variable across multiple functions called back to back, especially not a GoTweenFlow. Can we make it so that there is one GoTweenFlow that is responsible for handling the entire reward sequence? Or up until a certain point where we wait for user input?

2022-11-04 02:18 UTC, ptp-education commented on Assets/scripts/episodes/lego_4/SpawnedWallMomo.cs
> -                    if (onGoing_) return;
Shouldn't we be checking if flow_ is running at some point, or we are waiting for user input? For example the options holder is visible.

2022-11-07 18:20 UTC, benjaminZarate commented on Assets/scripts/episodes/lego_4/SpawnedWallMomo.cs
> +        flow_ = new GoTweenFlow();
I test some functions of flow to clean up the tweens so they dont repeat when we don't need it but it didin't worked, just cause more bugs. What I did now is to try to reduce the amount of times to instatiate the flow variable but I know is not the right way to do it. Maybe should we stick to the boolean variable?

2022-11-09 22:16 UTC, merged